### ISSUE TITLE
"confmacs select" breaks when .emacs.d not present

### ISSUE THREAD

**Issue by wallacewinfrey** [SShrike/confmacs#7]
Had to do a fresh install on my MBP running OSX Yosemite. Had no previous `.emacs.d` folder created. Here's the output of `confmacs select` when `.emacs.d` does not exist:

```
confmacs select spacemacs
~/.emacs.d will be deleted and replaced with a symlink.
Do you want to proceed? (Y/N)
Y
/Users/username/.anyenv/envs/rbenv/versions/2.3.0/lib/ruby/2.3.0/fileutils.rb:1300:in `open': Permission denied @ dir_initialize - /Users/wwinfrey/.emacs.d (Errno::EACCES)
    from /Users/username/.anyenv/envs/rbenv/versions/2.3.0/lib/ruby/2.3.0/fileutils.rb:1300:in `entries'
    from /Users/username/.anyenv/envs/rbenv/versions/2.3.0/lib/ruby/2.3.0/fileutils.rb:1300:in `entries'
    from /Users/username/.anyenv/envs/rbenv/versions/2.3.0/lib/ruby/2.3.0/fileutils.rb:1487:in `postorder_traverse'
    from /Users/username/.anyenv/envs/rbenv/versions/2.3.0/lib/ruby/2.3.0/fileutils.rb:777:in `remove_entry'
    from /Users/username/.anyenv/envs/rbenv/versions/2.3.0/lib/ruby/2.3.0/fileutils.rb:805:in `remove_dir'
    from /Users/username/.anyenv/envs/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/confmacs-0.2.0/bin/confmacs:60:in `select'
    from /Users/username/.anyenv/envs/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Users/username/.anyenv/envs/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Users/username/.anyenv/envs/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /Users/username/.anyenv/envs/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /Users/username/.anyenv/envs/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/confmacs-0.2.0/bin/confmacs:76:in `<top (required)>'
    from /Users/username/.anyenv/envs/rbenv/versions/2.3.0/bin/confmacs:23:in `load'
    from /Users/username/.anyenv/envs/rbenv/versions/2.3.0/bin/confmacs:23:in `<main>'`
```

**Comment by severen** [comment]
Well that is odd, it works fine on both my Linux desktop and laptop. What are the permissions for your home directory?

**Comment by wallacewinfrey** [comment]
```
ls -ld ~/.
drwxr-xr-x+ 26 username  staff  884 Feb 27 19:44 /Users/username/.
```

**Comment by severen** [comment]
Just tried Confmacs on a Macbook running Yosemite and I haven't run into the same problem.

**Comment by wallacewinfrey** [comment]
Yeah, I dunno. I tried it with the system ruby/gem as well before using the rbenv-managed version, and got the same output. I'll try doing a `confmacs init` with `dtruss` when I get a moment.

**Comment by severen** [comment]
Sweet, I'll do the same on the Macbook I have. :+1:
