### ISSUE TITLE
[Solved]Thor 0.20.0 support

### ISSUE THREAD

**Issue by xxzozaxx** [SShrike/confmacs#8]
confmacs does not work and show this message

```
Traceback (most recent call last):
        8: from /bin/confmacs:23:in `<main>'
        7: from /usr/lib/ruby/2.5.0/rubygems.rb:309:in `activate_bin_path'
        6: from /usr/lib/ruby/2.5.0/rubygems.rb:309:in `synchronize'
        5: from /usr/lib/ruby/2.5.0/rubygems.rb:310:in `block in activate_bin_path'
        4: from /usr/lib/ruby/2.5.0/rubygems/specification.rb:1440:in `activate'
        3: from /usr/lib/ruby/2.5.0/rubygems/specification.rb:1458:in `activate_dependencies'
        2: from /usr/lib/ruby/2.5.0/rubygems/specification.rb:1458:in `each'
        1: from /usr/lib/ruby/2.5.0/rubygems/specification.rb:1469:in `block in activate_dependencies'
/usr/lib/ruby/2.5.0/rubygems/dependency.rb:312:in `to_specs': Could not find 'thor' (~> 0.19.1) - did find: [thor-0.20.0] (Gem::MissingSpecVersionError)
Checked in 'GEM_PATH=/home/master/.gem/ruby/2.5.0:/usr/lib/ruby/gems/2.5.0:/home/master/.gem', execute `gem env` for more information
```

gem env output:
```
RubyGems Environment:
  - RUBYGEMS VERSION: 2.7.6
  - RUBY VERSION: 2.5.1 (2018-03-29 patchlevel 57) [x86_64-linux]
  - INSTALLATION DIRECTORY: /home/master/.gem
  - USER INSTALLATION DIRECTORY: /home/master/.gem/ruby/2.5.0
  - RUBY EXECUTABLE: /usr/bin/ruby
  - EXECUTABLE DIRECTORY: /home/master/.gem/bin
  - SPEC CACHE DIRECTORY: /home/master/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /home/master/.gem
     - /home/master/.gem/ruby/2.5.0
     - /usr/lib/ruby/gems/2.5.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "gem" => "--user-install"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /home/master/.zplug/repos/zplug/zplug/bin
     - /home/master/.zplug/bin
     - /home/master/.gem/ruby/2.5.0/bin
... etc
```

**Comment by xxzozaxx** [comment]
Solved; I just run
`gem install confmacs`.

I was install it from AUR. this problem in AUR package
